<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */
$translate = $this->plugin('translate');

// Geosearch.
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-providers/leaflet-providers.min.js', 'Cartography'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-geosearch/style.css', 'Cartography'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-geosearch/leaflet.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-geosearch/bundle.min.js', 'Cartography'));

// Add wms layers if any.
if ($wmsLayers) {
    $this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-markercluster/MarkerCluster.css', 'Cartography'));
    $this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-markercluster/MarkerCluster.Default.css', 'Cartography'));
    $this->headScript()->appendFile($this->assetUrl('vendor/leaflet-markercluster/leaflet.markercluster.js', 'Cartography'));
    $this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.min.css', 'Cartography'));
    $this->headScript()->appendFile($this->assetUrl('vendor/leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.min.js', 'Cartography'));
    // From module Mapping.
    $this->headScript()->appendFile($this->assetUrl('js/control.opacity.js', 'Cartography'));
}

// Add wmts layers if needed.
if (!empty($jsLocate)) {
    // $this->headScript()->appendFile($this->assetUrl('vendor/leaflet-tilelayer-wmts/leaflet-tilelayer-wmts.js', 'Cartography'));
    $this->headScript()->appendFile($this->assetUrl('vendor/leaflet-tilelayer-wmts/leaflet-tilelayer-wmts-src.js', 'Cartography'));
}

// Integration in Omeka S.
$jsLocate = empty($jsLocate) ? '' : '
$(document).ready( function() {
' . $jsLocate . '
});';
$script = 'var wmsLayers = ' . json_encode($wmsLayers, 320) . ';' . $jsLocate;
$this->headScript()->appendScript($script);
$this->headScript()->appendFile($this->assetUrl('js/cartography-admin-locate.js', 'Cartography'));

?>
<fieldset id="locate" class="section">
    <legend id="cartography-legend"><?php echo $translate('Geolocate item'); ?></legend>
    <div id="cartography-map" style="height:800px;"></div>
    <div class="description"><?php echo $this->setting('cartography_user_guide'); ?></div>
</fieldset>
