<?php
/** @var \Zend\View\Renderer\PhpRenderer $this */

// The module is independant from the module Mapping, but some js are the same,
// so it is recommenced to choose one module or the other to avoid js conflicts.
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet/leaflet.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet/leaflet.js', 'Cartography'));

// Edition via draw.
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-draw/leaflet.draw.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-draw/leaflet.draw.js', 'Cartography'));

// Style editor.
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-styleeditor/css/Leaflet.StyleEditor.min.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-styleeditor/javascript/Leaflet.StyleEditor.min.js', 'Cartography'));

// Leaflet paste.
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-paste/css/Leaflet.paste.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-paste/vendor/wicket.src.js', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-paste/vendor/wicket-leaflet.src.js', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-paste/js/Leaflet.Layer.WKT.js', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-paste/js/Leaflet.paste.js', 'Cartography'));

// Leaflet terraformer.
// TODO See if terraformer can replace leaflet paste.
$this->headScript()->appendFile($this->assetUrl('vendor/terraformer/terraformer.min.js', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/terraformer-arcgis-parser/terraformer-arcgis-parser.min.js', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/terraformer-wkt-parser/terraformer-wkt-parser.min.js', 'Cartography'));

// Leaflet full screen (full view).
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-fullscreen/leaflet.fullscreen.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-fullscreen/Leaflet.fullscreen.min.js', 'Cartography'));

// TODO Fit bounds and default view (js from module Mapping).
// $this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Cartography'));
// $this->headScript()->appendFile($this->assetUrl('js/control.default-view.js', 'Cartography'));

// Integration in Omeka S.
$this->headLink()->appendStylesheet($this->assetUrl('css/cartography-admin.css', 'Cartography'));
// TODO Load only the item selector part of the resource-form.js.
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));

$script = 'var basePath = ' . json_encode($this->basePath(), 320) . ';
var resourceId = ' . $resource->id() . ';
var valuesJson =  ' . json_encode($resource->values(), 320). ';
var oaMotivatedBySelect = ' . json_encode($oaMotivatedBySelect, 320) . ';
var oaHasPurposeSelect = ' . json_encode($oaHasPurposeSelect, 320) . ';
var cartographyUncertaintySelect = ' . json_encode($cartographyUncertaintySelect, 320) . ';';
$this->headScript()->appendScript($script);

?>
<?php echo $this->partial('common/resource-select-sidebar'); ?>
