<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
$translate = $this->plugin('translate');

// Geosearch.
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-providers/leaflet-providers.min.js', 'Cartography'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-geosearch/style.css', 'Cartography'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-geosearch/leaflet.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-geosearch/bundle.min.js', 'Cartography'));

// Add wms layers if any (may be added in the config or in the resource).
// TODO Load wms js only if there are wms layers (the list is loaded dynamically).
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-markercluster/MarkerCluster.css', 'Cartography'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-markercluster/MarkerCluster.Default.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-markercluster/leaflet.markercluster.js', 'Cartography'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.min.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet-groupedlayercontrol/leaflet.groupedlayercontrol.min.js', 'Cartography'));
// From module Mapping.
$this->headScript()->appendFile($this->assetUrl('js/control.opacity.js', 'Cartography'));

// Integration in Omeka S.
if ($js = $this->setting('cartography_js_locate')) {
    // Add wmts layers if needed.
    // $this->headScript()->appendFile($this->assetUrl('vendor/leaflet-tilelayer-wmts/leaflet-tilelayer-wmts.js', 'Cartography'));
    $this->headScript()->appendFile($this->assetUrl('vendor/leaflet-tilelayer-wmts/leaflet-tilelayer-wmts-src.js', 'Cartography'));
    $js = '$(document).ready( function() { ' . $js . ' });';
}
$js .= "cartographySections.push('locate');";
$this->headScript()->appendScript($js);

?>
<fieldset id="locate" class="section">
    <legend><?php echo $translate('Geolocate resource'); ?></legend>
    <div id="annotate-locate" style="height:600px;"></div>
    <div class="description"><?php echo $this->setting('cartography_user_guide'); ?></div>
</fieldset>
