<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
$translate = $this->plugin('translate');

// Integration in Omeka S.
if ($js = $this->setting('cartography_js_describe')) {
    $js = '$(document).ready( function() { ' . $js . ' });';
}
$js .= "cartographySections.push('describe');";
$this->headScript()->appendScript($js);

?>
<fieldset id="describe" class="section">
    <legend><?php echo $translate('Annotate an image'); ?></legend>
    <div id="annotate-describe" style="height:600px;"></div>
    <div class="description"><?php echo $this->setting('cartography_user_guide'); ?></div>
</fieldset>
