<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $options
 */

$translate = $this->plugin('translate');
?>
<?php if ($options['annotate']): ?>

<?php if ($options['type'] === 'describe'): ?>
<fieldset id="describe" class="section cartography-section">
    <legend><?php echo $translate('Annotate an image'); ?></legend>
    <div id="annotate-describe" class="cartography-map"></div>
    <div class="cartography-guide"><?php echo $this->setting('cartography_user_guide'); ?></div>
</fieldset>
<?php elseif ($options['type'] === 'locate'): ?>
<fieldset id="locate" class="section cartography-section">
    <legend><?php echo $translate('Geolocate resource'); ?></legend>
    <div id="annotate-locate" class="cartography-map"></div>
    <div class="cartography-guide"><?php echo $this->setting('cartography_user_guide'); ?></div>
</fieldset>
<?php endif; ?>

<?php else: ?>

<?php if ($options['type'] === 'describe'): ?>
<fieldset id="describe" class="section cartography-section">
    <legend><?php echo $translate('Image annotations'); ?></legend>
    <div id="annotate-describe" class="cartography-map"></div>
</fieldset>
<?php elseif ($options['type'] === 'locate'): ?>
<fieldset id="locate" class="section cartography-section">
    <legend><?php echo $translate('Georeferenced annotations'); ?></legend>
    <div id="annotate-locate" class="cartography-map"></div>
</fieldset>
<?php endif; ?>

<?php endif; ?>
