<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $options
 */

$translate = $this->plugin('translate');
?>
<?php if ($options['annotate']): ?>

<?php if ($options['type'] === 'describe'): ?>
<div id="describe" class="section">
    <h3><?php echo $translate('Annotate an image'); ?></h3>
    <div id="annotate-describe" style="height:600px;"></div>
    <div class="description"><?php echo $this->setting('cartography_user_guide'); ?></div>
</div>
<?php elseif ($options['type'] === 'locate'): ?>
<div id="locate" class="section">
    <h3><?php echo $translate('Geolocate resource'); ?></h3>
    <div id="annotate-locate" style="height:600px;"></div>
    <div class="description"><?php echo $this->setting('cartography_user_guide'); ?></div>
</div>
<?php endif; ?>

<?php else: ?>

<?php if ($options['type'] === 'describe'): ?>
<div id="describe" class="section">
    <h3><?php echo $translate('Image annotations'); ?></h3>
    <div id="annotate-describe" style="height:600px;"></div>
</div>
<?php elseif ($options['type'] === 'locate'): ?>
<div id="locate" class="section">
    <h3><?php echo $translate('Georeferenced annotations'); ?></h3>
    <div id="annotate-locate" style="height:600px;"></div>
</div>
<?php endif; ?>

<?php endif; ?>
