<?php
$translate = $this->plugin('translate');

// The module is independant from the module Mapping, but some js are the same,
// so it is recommenced to choose one module or the other.
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet/leaflet.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet/leaflet.js', 'Cartography'));

// Edition via draw.
// $this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.draw/leaflet.draw.css', 'Cartography'));
// $this->headScript()->appendFile($this->assetUrl('vendor/leaflet.draw/leaflet.draw.js', 'Cartography'));

// Geosearch.
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.providers/leaflet-providers.js', 'Cartography'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.geosearch/style.css', 'Cartography'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.geosearch/leaflet.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.geosearch/bundle.min.js', 'Cartography'));

// Style editor.
// $this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.StyleEditor/css/Leaflet.StyleEditor.min.css', 'Cartography'));
// $this->headScript()->appendFile($this->assetUrl('vendor/leaflet.StyleEditor/javascript/Leaflet.StyleEditor.min.js', 'Cartography'));

// Specific libraries.
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.fullscreen/leaflet.fullscreen.css', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.fullscreen/Leaflet.fullscreen.min.js', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/terraformer/terraformer.min.js', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/terraformer-arcgis-parser/terraformer-arcgis-parser.min.js', 'Cartography'));
$this->headScript()->appendFile($this->assetUrl('vendor/terraformer-wkt-parser/terraformer-wkt-parser.min.js', 'Cartography'));

// Integration in Omeka S.
$this->headScript()->appendFile($this->assetUrl('js/cartography.js', 'Cartography'));
$this->headScript()->prependScript('var basePath = ' . json_encode($this->basePath(), 320) . ';
var resourceId = ' . $resource->id() . ';');

// TODO Fit bounds and default view.
// Js from Mapping that should be appended last.
// $this->headScript()->appendFile($this->assetUrl('js/control.opacity.js', 'Cartography'));
// $this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Cartography'));
// $this->headScript()->appendFile($this->assetUrl('js/control.default-view.js', 'Cartography'));

?>
<fieldset id="cartography" class="section">
    <legend id="cartography-legend"><?php echo $translate('Cartography'); ?></legend>
    <div id="cartography-map" style="height:500px;"></div>
</fieldset>
<script type="text/javascript">
//<!--
var geometries = <?php echo json_encode($geometries, 320); ?>;
//-->
</script>
