<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Annotate\Api\Representation\AnnotationRepresentation[] $resources
 * @var \Annotate\Api\Representation\AnnotationRepresentation[] $annotations
 */

// $query = $this->params()->fromQuery(); // Use the helper.

$translate = $this->plugin('translate');

$this->cartography();

$this->htmlElement('body')->appendAttribute('class', 'annotations cartography browse');
?>
<?php echo $this->pageTitle('', 1, $translate('Georeferenced annotations')); ?>
<?php $this->trigger('view.browse.before'); ?>

<div id="annotate-geobrowse" style="height:600px;"></div>

<?php $this->trigger('view.browse.after'); ?>
